### ISSUE TITLE
Configuration: Add `enabled` flag for email config

### ISSUE THREAD

**Issue by charmitro** [terra-sync/cnc#28]
Currently, email configuration does not have a toggle field (i.e. `enabled = true` or `enabled = false`), let's introduce it.

Another idea of mine is: Should we also have `email = true` on database sections in the configurations? For example,

Working:
```ini
[postgres]
email = true

[email]
enabled = true
```

Not working:
```ini
[postgres]
email = true

[email]
enabled = false
```

Not working (email disabled by default)
```ini
[postgres]
email = true
```

@panosfol Share your thoughts on this.

**Comment by panosfol** [comment]
So if we have an email field for each database section, that means that we notify the user for the databases that have email enabled, while ignoring the others right? I dont see a particular reason for someone to use our tool for lets say 3 different  database systems, but receive an email for only 2. I think it complicates our `.ini` for no actual benefit.

**Comment by panosfol** [comment]
Ok thats a really good point, I'll go ahead and implement it.

**Comment by charmitro** [comment]
I think we should move this and https://github.com/terra-sync/cnc/issues/24 for milestone v0.2.0. What do you think @panosfol ?

I also want to discuss the addition of Rust to our codebase, with first feature of it being email.

**Comment by panosfol** [comment]
> I think we should move this and https://github.com/terra-sync/cnc/issues/24 for milestone v0.2.0. What do you think @panosfol ?
> 
> I also want to discuss the addition of Rust to our codebase, with first feature of it being email.
> 

Yes I agree.
About rust, you thinking we refractor the whole email process using rust? What's the benefits of it?

**Comment by charmitro** [comment]
> About rust, you thinking we refractor the whole email process using rust? What's the benefits of it? 

Easier to format email body and send out multiple emails, preferably using lettre-rs.

**Comment by charmitro** [comment]
Plus, I'd really like to the showcase Rust's power, and also Rust <-> C bindings power.
