### ISSUE TITLE
Read email body from file

### ISSUE THREAD

**Issue by charmitro** [terra-sync/cnc#47]
Currently the email body is passed to our Rust `send_email` function via a `*const c_char` argument,

https://github.com/terra-sync/cnc/blob/9fe43151a1c7adb0297ad7eb68c282ab9f7714e7/rust/email/src/lib.rs#L17

With the completion of #46 we'd need to change this to accept a filename, and use the files content for the email body.

**Comment by charmitro** [comment]
Cc @zycon91

This should be fairly easy to implement if you're interested.

**Comment by zycon91** [comment]
> Cc @zycon91
> 
> This should be fairly easy to implement if you're interested.

I will take a look at it. Seems quite simple with a quick first look.

**Comment by charmitro** [comment]
> > Cc @zycon91
> > This should be fairly easy to implement if you're interested.
> 
> I will take a look at it. Seems quite simple with a quick first look.

Sure! Take your time, @panosfol need to fix #46 first.

**Comment by charmitro** [comment]
@zycon91 No longer blocked, self-assign if you're still interested.
