### ISSUE TITLE
Minor issues to be fixed

### ISSUE THREAD

**Issue by panosfol** [terra-sync/cnc#48]
This issue keeps track of all the general issues that need attention in our codebase:

- [ ] `db.c:36` : we should not return if the connection fails in one of the databases.
- [ ] `postgres.c` : there are `malloc`'d values that are not freed, should the connection with postgres fails. 
(This might lead to a bigger issue of keeping track of all the pointers that need to be freed in the various stages of the replication progress.)

**Comment by charmitro** [comment]
>  [ ]  `db.c:36` : we should not return if the connection fails in one of the databases.

Not sure about that... 

Let's think this scenario
---
A user has 2 databases in his config file, a postgres and a Mongo (assuming we support it) and first in operation is Postgres, which fails for whatever reason, does he want to continue with Mongo replication?

>  [ ]  `postgres.c` : there are `malloc`'d values that are not freed, should the connection with postgres fails.
>       (This might lead to a bigger issue of keeping track of all the pointers that need to be freed in the various stages of the replication progress.)

I'll investigate and return to this later.

**Comment by panosfol** [comment]
> > [ ]  `db.c:36` : we should not return if the connection fails in one of the databases.
> 
> Not sure about that...
> 
> ## Let's think this scenario
> A user has 2 databases in his config file, a postgres and a Mongo (assuming we support it) and first in operation is Postgres, which fails for whatever reason, does he want to continue with Mongo replication?
> 
> > [ ]  `postgres.c` : there are `malloc`'d values that are not freed, should the connection with postgres fails.
> > (This might lead to a bigger issue of keeping track of all the pointers that need to be freed in the various stages of the replication progress.)
> 
> I'll investigate and return to this later.

Yes i believe he should continue with Mongo replication. If a user tries to replicate a lot of databases
and he made a mistake in the configuration, shouldn't he just 'lose' replication process on only one?
There is some time wasted for him if all failed right?
